---
- name: use the package module
  hosts: parag
  vars:
  - packets:
    - httpd
    - nfs

  tasks:
  - name: upgrade the nfs and https package
    service:
      name: '{{ item }}'
      state: started
    with_items:
      - '{{ packets }}'

  - debug:
      msg: the http and nfs service are present

  - name: now install the following package
    package:
      name:
      - httpd
      - nfs-utils
      state: latest
