---
- name: service module
  hosts: parag
  tasks:
  - name: start the http service
    service:
      name: httpd
      state: started

  - name: now stop the service
    yum: 
      name: epel-release
      state: absent
  
  - name: to install the nfs package
    yum:
      name: epel-release
      state: installed
 
#  - name: now start the nfs service
#    service:
#      name: nfs
#      state: started
