name: Ansible CI

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize, closed]
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  ansible-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Run Ansible Lint
        run: |
          pip install ansible-lint
          ansible-lint playbooks/

      # Optional: Run a playbook
      - name: Run Ansible Playbook
        run: |
          ansible-playbook playbooks/site.yml -i inventory.ini
